name: jusel_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  drift: ^2.29.0
  drift_flutter: ^0.2.7
  path_provider: ^2.1.5
  firebase_core: ^4.2.1
  firebase_auth: ^6.1.2
  cloud_firestore: ^6.1.0
  intl: ^0.20.2
  flutter_riverpod: ^2.6.1
  # third-party packages removed per request

dev_dependencies:
  flutter_test:
    sdk: flutter
  drift_dev: ^2.29.0
  build_runner: ^2.10.4
  # developer packages removed per request

flutter:
  uses-material-design: true
